%% Requirements:
%  1. DeltaDelayZ shall only be defined by input/output dimensions and
%      timestep
%  2. Upon construction, and when queried by user, it shall display the
%      information described in (1), with the name and type being "Z" and 
%      "delay operator", respectively.
%  3. If dimension information is not provided by the user, by
%      default the object shall be 1 x 1.
%  4. If timestep information is not provided by the user, by default the
%      object shall have an empty (or undefined) timestep
%
%  5. If the user provides an in/out dimension that is not a natural number
%      DeltaDelayZ shall throw an exception
%  6. If the users provides a timestep less than or equal to zero,
%      DeltaDelayZ shall throw an exception
%
%  7. DeltaDelayZ shall return the null mappings and the same DeltaDelayZ
%      object, without throwing a warning, when queried for normalization.

%%
%  Copyright (c) 2021 Massachusetts Institute of Technology 
%  SPDX-License-Identifier: GPL-2.0
%%

%% Test class for DeltaDelayZ.
classdef testDeltaDelayZ < matlab.unittest.TestCase
    
    methods (TestMethodSetup)
        function seedAndReportRng(testCase)
            seed = floor(posixtime(datetime('now')));
            rng('default');
            rng(seed);
            diagnose_str = ...
                sprintf(['Random inputs may be regenerated by calling: \n',...
                         '>> rng(%10d) \n',...
                         'before running the remainder of the test''s body'],...
                        seed);
            testCase.onFailure(@() fprintf(diagnose_str));
        end    
    end
    
    methods (Test)
        function testFullConstructor(testCase)
            dim_outin = 3;
            timestep = 0.5;
            delta_delay_z = DeltaDelayZ(dim_outin, timestep);
            verifyEqual(testCase, delta_delay_z.name, 'Z')
            verifyEqual(testCase, delta_delay_z.dim_in, dim_outin)
            verifyEqual(testCase, delta_delay_z.dim_out, dim_outin)
            verifyEqual(testCase, delta_delay_z.dim_in, delta_delay_z.dim_out)
            verifyEqual(testCase,...
                        delta_delay_z.timestep,...
                        timestep)
        end
        
        function testOneArgConstructor(testCase)
            dim_outin = 2;
            delta_delay_z = DeltaDelayZ(dim_outin);
            verifyEqual(testCase, delta_delay_z.name, 'Z')
            verifyEqual(testCase, delta_delay_z.dim_in, dim_outin)
            verifyEqual(testCase, delta_delay_z.dim_out, dim_outin)
            verifyEqual(testCase, delta_delay_z.dim_in, delta_delay_z.dim_out)
        end

        function testZeroArgConstructor(testCase)
            delta_delay_z = DeltaDelayZ();
            verifyEqual(testCase, delta_delay_z.name, 'Z')
            verifyEqual(testCase, delta_delay_z.dim_in, 1)
            verifyEqual(testCase, delta_delay_z.dim_out, 1)
            verifyEqual(testCase, delta_delay_z.dim_in, delta_delay_z.dim_out)
        end

        function testFailedDimension(testCase)
            verifyError(testCase, @() DeltaDelayZ(-2), ?MException)
            verifyError(testCase, @() DeltaDelayZ(2.2), ?MException)
        end
        
        function testFailedTimestep(testCase)
            verifyError(testCase, @() DeltaDelayZ(1,0), ?MException)
            verifyError(testCase, @() DeltaDelayZ(1,-3), ?MException)
        end
        
        function testDisplayOneTimestep(testCase)
        % This test added due to the issue "hotfix-006". Should output to
        % command prompt the following:
        %     Z       is a   5 x 5       delay operator 
        %      with a timestep of 1.0e+00 seconds 
        %     Z       is a   5 x 5       delay operator 
        %      with a timestep of 1.0e-01 seconds         
            disp(DeltaDelayZ(5, 1, [3, 4]))
            disp(DeltaDelayZ(5, 0.1, [3, 4]))
        end
        
        function testNormalization(testCase)
            warning_state = warning;
            warning('error', 'Ulft:normalizeLft')            
            for i = 1:10
                lft = Ulft.random('num_deltas',1,'req_deltas',{'DeltaDelayZ'});
                % Check that no warning is thrown
                warning_thrown = false;
                try
                    lft_n = normalizeLft(lft);
                catch
                    warning_thrown = true;
                end
                verifyFalse(testCase, warning_thrown)
                % Check that lft is unchanged
                verifyEqual(testCase, lft_n, lft)
            end
            warning(warning_state)
        end
    end
end

%%  CHANGELOG
% Sep. 28, 2021 (v0.6.0)
% Aug. 26, 2021 (v.0.5.0): Initial release - Micah Fry (micah.fry@ll.mit.edu)